import Head from 'next/head'
import Image from 'next/image'
// import '../styles/base.scss'
// import { Inter } from '@next/font/google'
import Questionarie from '../src/components/Questionarie';
import styles from '../styles/Home.module.css'
import LinearProgress from '@mui/material/LinearProgress';

// const inter = Inter({ subsets: ['latin'] })
// #0755DB

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* <div className="container mx-auto">
          <div className="flex h-[90px] items-center px-4 md:px-0">
          <div className="grow">
            <div className="relative  min-w-[150px] max-w-[267px] md:h-[32px] md:min-w-none md:max-w-none md:w-[304px]  outline-none">
              <a title="AEF - Affordable Health Insurance Quotes, Short Term Medical Insurance" href="/" />

              <div className="absolute h-4 w-4 bottom-0 right-0 rounded-full border bg-[#11A56A]">
              </div>
            </div>
          </div>
        </div>
        </div> */}
        <Questionarie />
      </main>
    </>
  )
}
